README.md, ansible/group_vars/all.yml, ansible/inventory/hosts, ansible/roles/operators/tasks/main.yml, ansible/roles/operators/templates/performance-add-on-operator.yml.j2, ansible/tasks/validation.yml, ansible/vars/all.yml, ansible/webscale.yml
* Provies structure/organization to the repo
=> Initial commit

README.md, ansible/group_vars/all.yml, ansible/roles/bigip-ingress-setup/defaults/main.yml, ansible/roles/bigip-ingress-setup/tasks/30_sriov_network.yml, ansible/roles/bigip-ingress-setup/tasks/41_bigip_bridge_network.yml, ansible/roles/bigip-ingress-setup/tasks/42_bigip_data_volume.yml, ansible/roles/bigip-ingress-setup/templates/bigip-vars.yml.j2, ansible/roles/bigip-ingress-setup/templates/hostpath-prov.yaml.j2, ansible/roles/operators/defaults/main.yml, ansible/roles/operators/tasks/10_add_catalogsource.yml, ansible/roles/operators/tasks/99_csv_status.yml, ansible/roles/operators/tasks/99_mcp_status.yml, ansible/roles/operators/tasks/main.yml, ansible/roles/operators/templates/cluster-logging-operator.yml.j2, ansible/roles/operators/templates/elasticsearch-operator.yml.j2, ansible/roles/operators/templates/kafka-operator.yml.j2, ansible/roles/operators/templates/kubevirt-hyperconverged.yml.j2, ansible/roles/operators/templates/openshift-virtualization-operator.yml.j2, ansible/roles/operators/templates/performance-add-on-operator.yml.j2, ansible/roles/operators/templates/sriov-network-operator.yml.j2
=> Nightly operator installs

ansible/roles/bigip-ingress-setup/tasks/30_sriov_network.yml
Can run into issues like
https://gist.github.com/smalleni/21339fa7235c160ca10c0abc1662390f
otherwise.
=> Wait before applying SRIOV network node policy

.github/workflows/ansible-lint.yaml, ansible/configure-openshift-monitoring.yml, ansible/label-node.yml, ansible/local-storage.yml, ansible/remove-local-storage.yml, ansible/rhacm-hub.yml, ansible/rhacm-manage-cluster.yml, ansible/roles/bigip-ingress-setup/tasks/10_machine_setup.yml, ansible/roles/bigip-ingress-setup/tasks/30_sriov_network.yml, ansible/roles/bigip-ingress-setup/tasks/40_bigip_setup.yml, ansible/roles/bigip-ingress-setup/tasks/41_bigip_bridge_network.yml, ansible/roles/bigip-ingress-setup/tasks/42_bigip_data_volume.yml, ansible/roles/bigip-ingress-setup/tasks/43_provisioner_network.yml, ansible/roles/bigip-ingress-setup/tasks/45_bigip_vm.yml, ansible/roles/bigip-ingress-setup/tasks/50_bigip_activation.yml, ansible/roles/bigip-ingress-setup/tasks/60_bigip_ctrlr.yml, ansible/roles/bigip-ingress-setup/tasks/main.yml, ansible/roles/kafka-logging-setup/tasks/main.yml, ansible/roles/label_node/tasks/main.yml, ansible/roles/local_storage/tasks/main.yml, ansible/roles/operators/tasks/10_add_catalogsource.yml, ansible/roles/operators/tasks/99_csv_status.yml, ansible/roles/operators/tasks/main.yml, ansible/roles/remove_local_storage/tasks/main.yml, ansible/roles/rhacm_hub/tasks/main.yml, ansible/roles/rhacm_manage_cluster/tasks/main.yml, ansible/shiftstack-prepare-localstorage.yml, ansible/webscale.yml
=> Add ansible lint CI using GitHub Actions

ansible/group_vars/all.yml, ansible/rhacm-hub-downstream.yml, ansible/rhacm-hub.yml, ansible/roles/rhacm_hub_downstream/files/icsp.yaml, ansible/roles/rhacm_hub_downstream/tasks/main.yml, ansible/roles/rhacm_hub_downstream/templates/pull-secret.yaml.j2
Allows you to install rhacm 2.2
=> Add RHACM downstream install

README.md, ansible/group_vars/all.yml.sample, ansible/roles/openshift-monitoring-config/tasks/main.yml, ansible/roles/openshift-monitoring-config/templates/cluster-monitoring-config.yml.j2, ansible/roles/operators/tasks/main.yml, ansible/tasks/validation.yml, ansible/webscale.yml
Also includes changes to the cluster-monitoring-config
config to only apply changes using apply and also use
persistent storage.
=> Operator install rework and prometheus persistent storage config

ansible/roles/local_storage/tasks/main.yml
Jinja template file is missing.
=> copied missing template

ansible/group_vars/all.yml.sample, ansible/rhacm-assisted-installer.yml, ansible/roles/rhacm-assisted-installer/defaults/main.yml, ansible/roles/rhacm-assisted-installer/tasks/main.yml, ansible/roles/rhacm-assisted-installer/templates/agentserviceconfig.yml, ansible/roles/rhacm-assisted-installer/templates/assisted-mirror-config.yml
=> Enable assisted-installer in RHACM to be installed on disconnected/ipv6

ansible/roles/operators/defaults/4.6.yml
=> CNV stable version for 4.6

ansible/roles/bigip-ingress-setup/templates/hostpath-prov.yaml.j2
=> CNV stable for 4.6 expects boolean in hostpath-prov spec

ansible/roles/rhacm-assisted-installer/tasks/main.yml, ansible/roles/rhacm-hub-icsp/tasks/main.yml
assisted-installer install for non-disconnected clusters
=> Fix rhacm icsp to work for 3 node clusters and fix the

ansible/roles/operators/defaults/4.9.yml
This is lacking the defaults file for 4.9 installations, added that.
=> added defaults file for 4.9

ansible/roles/rhacm-assisted-installer/templates/assisted-mirror-config.yml
=> Yet another adjustment to the RHACM assisted-service mirror

ansible/roles/rhacm-assisted-installer/templates/agentserviceconfig.yml
=> Ensure rhacm's agentserviceconfig with openShiftVersion can handle `4.9`

ansible/roles/aspenmesh-servicemesh-setup/defaults/4.9.yml, ansible/roles/bigip-ingress-setup/tasks/41_bigip_bridge_network.yml, ansible/roles/bigip-ingress-setup/tasks/45_bigip_vm.yml, ansible/roles/operators/defaults/4.10.yml, ansible/roles/trident-storage-setup/defaults/4.9.yml
- Included 4.9 var file for trident and aspenmesh
- Included 4.10 nightly operator vars
- NNCP status change for 4.10
=> updates for nightly

ansible/group_vars/all.yml.sample, ansible/roles/rhacm-hub-deploy/tasks/main.yml, ansible/roles/rhacm-ztp-setup/defaults/main.yml, ansible/roles/rhacm-ztp-setup/tasks/main.yml
=> Migrate the gitops patches to the rhacm install instead of ztp repo

ansible/roles/rhacm-add-clusterimagesets/tasks/main.yml
old clusterimagesets from polluting the cluster
=> Remove old clusterimageset directory before newly templating it to avoid

ansible/group_vars/all.yml.sample, ansible/roles/rhacm-ztp-setup/tasks/main.yml, ansible/roles/rhacm-ztp-setup/templates/cluster-kustomization.yaml
=> Migrate the pre-siteconfig manifests into the resources section of the

ansible/roles/rhacm-ztp-setup/defaults/main.yml, ansible/roles/rhacm-ztp-setup/templates/common-ranGen.yaml
=> Allow adjusting of the ZTP du profile catalog source name to workaround

ansible/group_vars/all.yml.sample
catalog is missing too many performance changes
=> Adjust TALM defaults back to repo deployment since operator from the

ansible/roles/rhacm-ztp-setup/defaults/main.yml, ansible/roles/rhacm-ztp-setup/tasks/main.yml, ansible/roles/rhacm-ztp-setup/templates/common-ranGen.yaml, ansible/roles/rhacm-ztp-setup/templates/logging-openshift-io_elasticsearches.yaml
excessive load against ACM policy propagator
=> Add CLO CRD that prevents operator from crashlooping and putting
